# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 893c9d30b47867057ec515f988f3f2ac3a6765dd3f64eb470d0aec0b30ba0ad827f8b21aaccc89714fc3579478fb9aa852ffb0921b6d4e69199455ff33ac969a

test:
  secret_key_base: 2efe77b67cbbd2f301da14cf23cf33f3c4941ab188070e2b45a121af05e1b288e2aebb25e2d71af3c893a2b786163b63b7313f0d042a602a924d1933c77e40cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
